[build-system]
requires = ["setuptools>=66.1.0", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[tool.uv]
link-mode = "copy"
index-strategy = "unsafe-best-match"

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
paddlefleet-ops = { workspace = true }
paddlepaddle-gpu = { index = "paddlepaddle-gpu" }
paddlepaddle-xpu = { index = "paddlepaddle-xpu" }
paddle-nvidia-nvshmem-cu12 = { index = "paddlepaddle-gpu" }
paddle-nvidia-nvshmem-cu13 = { index = "paddlepaddle-cu13" }

[[tool.uv.index]]
name = "paddlepaddle-gpu"
url = "https://www.paddlepaddle.org.cn/packages/nightly/cu129/"

[[tool.uv.index]]
name = "paddlepaddle-cu13"
url = "https://www.paddlepaddle.org.cn/packages/nightly/cu130/"

[[tool.uv.index]]
name = "paddlepaddle-xpu"
url = "https://www.paddlepaddle.org.cn/packages/nightly/xpu-p800/"

[tool.isort]
profile = 'black'
known_third_party = ["paddle"]
skip = ['paddleformers/transformers/__init__.py']

[tool.black]
line-length = 119
target_version = ['py35', 'py36', 'py37', 'py38', 'py39', 'py310']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q "
pythonpath = ["."]
testpaths = [
    "tests/data",
    "tests/dataset",
    "tests/generation",
    "tests/mergekit",
    "tests/nn",
    "tests/peft",
    "tests/trainer",
    "tests/transformers",
    "tests/utils",
    "tests/ai_edited_test/cli",
    "tests/ai_edited_test/data",
    "tests/ai_edited_test/datasets",
    "tests/ai_edited_test/nn",
    "tests/ai_edited_test/peft",
    "tests/ai_edited_test/quantization",
    "tests/ai_edited_test/trainer",
    "tests/ai_edited_test/transformers",
    "tests/ai_edited_test/utils",
]
python_files = [
    "test.py",
    "test_*.py"
]
filterwarnings = [
    "ignore::UserWarning",
    'ignore::DeprecationWarning',
]
