qwen3moe:
    repo_id: PaddleFormers/tiny-random-qwen3moev2
    model_type: text
    cli_args:
        template: qwen3
        save_checkpoint_format: flex_checkpoint
        load_checkpoint_format: flex_checkpoint
qwen2_moe:
    repo_id: PaddleFormers/tiny-random-qwen2moev2
    model_type: text
    cli_args:
        template: qwen
qwen3:
    repo_id: PaddleFormers/tiny-random-qwen3v2
    model_type: text
    cli_args:
        template: qwen3
glm_moe:
    repo_id: PaddleFormers/tiny-random-glm4moe-bf16
    model_type: text
    cli_args:
        template: glm4_moe
qwen2:
    repo_id: PaddleFormers/tiny-random-qwen2v2
    model_type: text
    cli_args:
        template: qwen
llama:
    repo_id: PaddleFormers/tiny-random-llama3
    model_type: text
    cli_args:
        save_checkpoint_format: flex_checkpoint
        load_checkpoint_format: flex_checkpoint
        template: llama3
qwen3_next:
    repo_id: PaddleFormers/tiny-random-qwen3next
    model_type: text
    cli_args:
        save_checkpoint_format: flex_checkpoint
        load_checkpoint_format: flex_checkpoint
        template: qwen3
phi3:
    repo_id: PaddleFormers/tiny-random-phi4-bf16
    model_type: text
    cli_args:
        save_checkpoint_format: flex_checkpoint
        load_checkpoint_format: flex_checkpoint
        template: phi4
gemma3_text:
    repo_id: PaddleFormers/tiny-random-gemma3
    model_type: text
    cli_args:
        save_checkpoint_format: flex_checkpoint
        load_checkpoint_format: flex_checkpoint
        tensor_model_parallel_size: 1
        sequence_parallel: false
        template: gemma
deepseek_v3:
    repo_id: PaddleFormers/tiny-random-deepseek-v3
    model_type: text
    cli_args:
        template: deepseek3
paddleocr_vl:
    repo_id: PaddleFormers/tiny-random-paddleocr-vl-bf16
    model_type: vl
    cli_args:
        template: ernie_vl_nothink
        train_dataset_path: ./tests/fixtures/dummy/sft-vl/ocr_vl_sft-train_Bengali.jsonl
        eval_dataset_path: ./tests/fixtures/dummy/sft-vl/ocr_vl_sft-test_Bengali.jsonl
        train_dataset_type: messages
        eval_dataset_type: messages
        random_shuffle: false
        dataloader_shuffle: false
        freeze_config: ''