qwen3moe:
  repo_id: "PaddleFormers/tiny-random-qwen3moev2"
  cli_args: 
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full
    sft_full_loss: 12.949948
    sft_full_resume_loss: 12.948372
    dpo_full_loss: 0.693147
    dpo_full_resume_loss: 0.689683
    pt_full_loss: 12.973605
    pt_full_resume_loss: 12.966102
    # test_lora
    sft_lora_loss: 12.913843
    sft_lora_resume_loss: 12.979932
    dpo_lora_loss: 0.693147
    dpo_lora_resume_loss: 0.700489
    pt_lora_loss: 12.998665
    pt_lora_resume_loss: 12.953691
    #test_tp_pp
    sft_full_tp_pp_loss: 12.972793
    sft_full_tp_pp_resume_loss: 12.974055
    dpo_full_tp_pp_loss: 0.693147
    dpo_full_tp_pp_resume_loss: 0.695402
    pt_full_tp_pp_loss: 12.96485
    pt_full_tp_pp_resume_loss: 12.95455
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 12.972793
    sft_lora_tp_pp_resume_loss: 12.972111
    dpo_lora_tp_pp_loss: 0.696846
    dpo_lora_tp_pp_resume_loss: 0.696846
    pt_lora_tp_pp_loss: 12.96485
    pt_lora_tp_pp_resume_loss: 12.954285
    #test_fc
    sft_full_function_call_loss: 12.90508
    sft_full_function_call_resume_loss: 12.913303
# qwen2_moe:
#   repo_id: "PaddleFormers/tiny-random-qwen2moev2"
#   base_loss: 
#     # test_full 
#     sft_full_loss: 12.993172
#     sft_full_resume_loss: 12.97237
#     dpo_full_loss: 0.693147
#     dpo_full_resume_loss: 0.692849
#     pt_full_loss: 12.856025
#     pt_full_resume_loss: 12.85647
#     # test_lora
#     sft_lora_loss: 12.993172
#     sft_lora_resume_loss: 12.972338
#     dpo_lora_loss: 0.693147
#     dpo_lora_resume_loss: 0.694667
#     pt_lora_loss: 12.856025
#     pt_lora_resume_loss: 12.856522

#     #test_tp_pp !
#     sft_full_tp_pp_loss: 12.992263
#     sft_full_tp_pp_resume_loss: 12.99057
#     dpo_full_tp_pp_loss: 0.69518
#     dpo_full_tp_pp_resume_loss: 0.699244
#     pt_full_tp_pp_loss: 12.761184
#     pt_full_tp_pp_resume_loss: 12.774579
#     #test_lora_tp_pp
#     sft_lora_tp_pp_loss: 12.992616
#     sft_lora_tp_pp_resume_loss: 12.99163
#     dpo_lora_tp_pp_loss: 11.944916
#     dpo_lora_tp_pp_resume_loss: 11.946712
#     pt_lora_tp_pp_loss: 12.761208
#     pt_lora_tp_pp_resume_loss: 12.774649
#     #test_fc
#     sft_full_function_call_loss: 12.813175
#     sft_full_function_call_resume_loss: 12.821417
# qwen3: 
#   repo_id: "PaddleFormers/tiny-random-qwen3"
#   cli_args: 
#     unified_checkpoint: false
#     save_checkpoint_format: flex_checkpoint
#     load_checkpoint_format: flex_checkpoint
#   base_loss: 
#     # test_full 
#     sft_full_loss: 11.944817
#     sft_full_resume_loss: 11.946183
#     dpo_full_loss: 0.693121
#     dpo_full_resume_loss: 0.693068
#     pt_full_loss: 11.975817
#     pt_full_resume_loss: 11.974206
#     # test_lora
#     sft_lora_loss: 11.944797
#     sft_lora_resume_loss: 11.946123
#     dpo_lora_loss: 0.693144
#     dpo_lora_resume_loss: 0.693138
#     pt_lora_loss: 11.975819
#     pt_lora_resume_loss: 11.97421
#     #test_tp_pp
#     sft_full_tp_pp_loss: 11.956945
#     sft_full_tp_pp_resume_loss: 11.956932
#     dpo_full_tp_pp_loss: 0.693137
#     dpo_full_tp_pp_resume_loss: 0.693116
#     pt_full_tp_pp_loss: 11.980651
#     pt_full_tp_pp_resume_loss: 11.98307
#     #test_lora_tp_pp
#     sft_lora_tp_pp_loss: 11.956937
#     sft_lora_tp_pp_resume_loss: 11.956906
#     dpo_lora_tp_pp_loss: 0.693104
#     dpo_lora_tp_pp_resume_loss:  0.693018
#     pt_lora_tp_pp_loss: 11.980649
#     pt_lora_tp_pp_resume_loss: 11.983072
#     #test_fc
#     sft_full_function_call_loss: 11.955276
#     sft_full_function_call_resume_loss: 11.950663

# glm_moe: 
#   repo_id: "PaddleFormers/tiny-random-glm4moe"
  # cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    # save_checkpoint_format: flex_checkpoint
    # load_checkpoint_format: flex_checkpoint
  # base_loss: 
  #   # test_full 
  #   sft_full_loss: 12.928021 
  #   sft_full_resume_loss: 12.92828
  #   dpo_full_loss: 0.691502
  #   dpo_full_resume_loss: 0.688213
  #   pt_full_loss: 13.030177
  #   pt_full_resume_loss: 13.04020
  #   # test_lora
  #   sft_lora_loss: 12.928604
  #   sft_lora_resume_loss: 11.946712
  #   dpo_lora_loss: 0.693131
  #   dpo_lora_resume_loss: 11.946712
  #   pt_lora_loss: 12.738609
  #   pt_lora_resume_loss: 11.946712
  #   #test_tp_pp
  #   sft_full_tp_pp_loss: 11.944916
  #   sft_full_tp_pp_resume_loss: 11.946712
  #   dpo_full_tp_pp_loss: 11.944916
  #   dpo_full_tp_pp_resume_loss: 11.946712
  #   pt_full_tp_pp_loss: 11.944916
  #   pt_full_tp_pp_resume_loss: 11.946712
  #   #test_lora_tp_pp
  #   sft_lora_tp_pp_loss: 11.944916
  #   sft_lora_tp_pp_resume_loss: 11.946712
  #   dpo_lora_tp_pp_loss: 11.944916
  #   dpo_lora_tp_pp_resume_loss: 11.946712
  #   pt_lora_tp_pp_loss: 11.944916
  #   pt_lora_tp_pp_resume_loss: 11.946712
  #   #test_fc
  #   sft_full_function_call_loss: 12.859377
  #   sft_full_function_call_resume_loss: 11.946712

# qwen2:
#   repo_id: "PaddleFormers/tiny-random-qwen2"
#   cli_args: 
#     fuse_attention_qkv: true
#     fuse_attention_ffn: true
#     save_checkpoint_format: flex_checkpoint
#     load_checkpoint_format: flex_checkpoint
#   base_loss: 
#     # test_full 
#     sft_full_loss: 11.944817
#     sft_full_resume_loss: 11.946183
#     dpo_full_loss: 0.693121
#     dpo_full_resume_loss: 0.693068
#     pt_full_loss: 11.975817
#     pt_full_resume_loss: 11.974206
#     # test_lora
#     sft_lora_loss: 11.944797
#     sft_lora_resume_loss: 11.946123
#     dpo_lora_loss: 0.693144
#     dpo_lora_resume_loss: 0.693138
#     pt_lora_loss: 11.975819
#     pt_lora_resume_loss: 11.97421
#     #test_tp_pp
#     sft_full_tp_pp_loss: 11.956945
#     sft_full_tp_pp_resume_loss: 11.956932
#     dpo_full_tp_pp_loss: 0.693137
#     dpo_full_tp_pp_resume_loss: 0.693116
#     pt_full_tp_pp_loss: 11.980651
#     pt_full_tp_pp_resume_loss: 11.98307
#     #test_lora_tp_pp
#     sft_lora_tp_pp_loss: 11.956937
#     sft_lora_tp_pp_resume_loss: 11.956906
#     dpo_lora_tp_pp_loss: 11.944916
#     dpo_lora_tp_pp_resume_loss: 11.946712
#     pt_lora_tp_pp_loss: 11.980649
#     pt_lora_tp_pp_resume_loss: 11.983072
#     #test_fc
#     sft_full_function_call_loss: 11.955276
#     sft_full_function_call_resume_loss: 11.950663

# deepseek_v3: 
#   repo_id: "PaddleFormers/tiny-random-deepseek-v3"
# ernie4_5:
#   repo_id: "hf-internal-testing/tiny-random-Ernie4_5Model"
# gpt_oss:  
#   repo_id: "PaddleFormers/tiny-random-gptoss"
# llama: 
#   repo_id: "Paddleformers/tiny-random-llama"