qwen3moe:
  repo_id: "PaddleFormers/tiny-random-qwen3moev2"
  cli_args: 
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full
    sft_full_loss: 12.949948
    sft_full_resume_loss: 12.948372
    dpo_full_loss: 0.693147
    dpo_full_resume_loss: 0.689683
    pt_full_loss: 12.973605
    pt_full_resume_loss: 12.966102
    # test_lora
    sft_lora_loss: 12.913843
    sft_lora_resume_loss: 12.979932
    dpo_lora_loss: 0.693147
    dpo_lora_resume_loss: 0.692318
    pt_lora_loss: 12.759583
    pt_lora_resume_loss: 12.766754
    #test_tp_pp
    sft_full_tp_pp_loss: 12.752461
    sft_full_tp_pp_resume_loss: 12.753006
    dpo_full_tp_pp_loss: 0.693147
    dpo_full_tp_pp_resume_loss: 0.696261
    pt_full_tp_pp_loss: 12.777053
    pt_full_tp_pp_resume_loss: 12.777079
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 12.972793
    sft_lora_tp_pp_resume_loss: 12.972111
    dpo_lora_tp_pp_loss: 0.693147
    dpo_lora_tp_pp_resume_loss: 0.692183
    pt_lora_tp_pp_loss: 12.96485
    pt_lora_tp_pp_resume_loss: 12.954285
    #test_fc
    sft_full_function_call_loss: 12.90508
    sft_full_function_call_resume_loss: 12.913303
qwen2_moe:
  repo_id: "PaddleFormers/tiny-random-qwen2moev2"
  cli_args: 
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 12.74101
    sft_full_resume_loss: 12.732811
    dpo_full_loss: 0.693147
    dpo_full_resume_loss: 0.692443
    pt_full_loss: 12.750682
    pt_full_resume_loss: 12.747829
    # test_lora
    sft_lora_loss: 12.810658
    sft_lora_resume_loss:  12.722644
    dpo_lora_loss: 0.693147
    dpo_lora_resume_loss: 0.692318
    pt_lora_loss: 12.759583
    pt_lora_resume_loss: 12.766771
    #test_tp_pp
    sft_full_tp_pp_loss: 12.992263
    sft_full_tp_pp_resume_loss: 12.99057
    dpo_full_tp_pp_loss: 0.693147
    dpo_full_tp_pp_resume_loss: 0.696261
    pt_full_tp_pp_loss: 12.761184
    pt_full_tp_pp_resume_loss: 12.774579
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 12.751438
    sft_lora_tp_pp_resume_loss: 12.75179
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 12.777053
    pt_lora_tp_pp_resume_loss:  12.776928
    #test_fc
    # sft_full_function_call_loss: 12.813175
    # sft_full_function_call_resume_loss: 12.821417
qwen3: 
  repo_id: "PaddleFormers/tiny-random-qwen3v2"
  cli_args: 
    unified_checkpoint: false
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
    fuse_attention_qkv: true
    fuse_attention_ffn: true
  base_loss: 
    # test_full 
    sft_full_loss: 12.756784
    sft_full_resume_loss: 12.742235
    dpo_full_loss: 0.693147
    dpo_full_resume_loss: 0.693794
    pt_full_loss: 12.88249
    pt_full_resume_loss: 12.879145
    # test_lora
    sft_lora_loss: 12.756784
    sft_lora_resume_loss: 12.742048
    dpo_lora_loss: 0.693147
    dpo_lora_resume_loss: 0.692916
    pt_lora_loss: 12.88249
    pt_lora_resume_loss: 12.879347
    #test_tp_pp
    sft_full_tp_pp_loss: 12.810429
    sft_full_tp_pp_resume_loss: 12.811285
    dpo_full_tp_pp_loss: 0.693147
    dpo_full_tp_pp_resume_loss:  0.693369
    pt_full_tp_pp_loss:  12.830297
    pt_full_tp_pp_resume_loss: 12.834314
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 12.810429
    sft_lora_tp_pp_resume_loss: 12.810394
    dpo_lora_tp_pp_loss: 0.693147
    dpo_lora_tp_pp_resume_loss:  0.693249
    pt_lora_tp_pp_loss: 12.830297
    pt_lora_tp_pp_resume_loss: 12.834597
    #test_fc
    sft_full_function_call_loss: 12.81908 
    sft_full_function_call_resume_loss: 12.791071
glm_moe: 
  repo_id: "PaddleFormers/tiny-random-glm4moe-bf16"
  cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 13.016921
    sft_full_resume_loss: 13.02186
    dpo_full_loss: 0.693147
    dpo_full_resume_loss: 0.693178
    pt_full_loss: 12.843946
    pt_full_resume_loss: 12.842224
    # test_lora
    sft_lora_loss: 13.016921
    sft_lora_resume_loss: 13.022078
    dpo_lora_loss: 0.693147
    dpo_lora_resume_loss: 0.693471
    pt_lora_loss: 12.843946 
    pt_lora_resume_loss: 12.842073
    #test_tp_pp
    sft_full_tp_pp_loss: 12.968091 
    sft_full_tp_pp_resume_loss: 12.968054
    dpo_full_tp_pp_loss: 0.693147
    dpo_full_tp_pp_resume_loss: 0.693764
    pt_full_tp_pp_loss: 12.834686
    pt_full_tp_pp_resume_loss: 12.828804
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 12.968091
    sft_lora_tp_pp_resume_loss: 12.968052
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 12.968091
    pt_lora_tp_pp_resume_loss: 12.968052
    #test_fc
    sft_full_function_call_loss: 12.859377
    sft_full_function_call_resume_loss: 11.946712
qwen2:
  repo_id: "PaddleFormers/tiny-random-qwen2v2"
  cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 11.944817
    sft_full_resume_loss: 11.946183
    dpo_full_loss: 0.693121
    dpo_full_resume_loss: 0.693068
    pt_full_loss: 11.975817
    pt_full_resume_loss: 11.974206
    # test_lora
    sft_lora_loss: 11.944797
    sft_lora_resume_loss: 11.946123
    dpo_lora_loss: 0.693144
    dpo_lora_resume_loss: 0.693138
    pt_lora_loss: 11.975819
    pt_lora_resume_loss: 11.97421
    #test_tp_pp
    sft_full_tp_pp_loss: 11.956945
    sft_full_tp_pp_resume_loss: 11.956932
    dpo_full_tp_pp_loss: 0.693137
    dpo_full_tp_pp_resume_loss: 0.693116
    pt_full_tp_pp_loss: 11.980651
    pt_full_tp_pp_resume_loss: 11.98307
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 11.956937
    sft_lora_tp_pp_resume_loss: 11.956906
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 11.980649
    pt_lora_tp_pp_resume_loss: 11.983072
    #test_fc
    sft_full_function_call_loss: 11.955276
    sft_full_function_call_resume_loss: 11.950663
llama: 
  repo_id: "PaddleFormers/tiny-random-llama3"
  cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 11.944817
    sft_full_resume_loss: 11.946183
    dpo_full_loss: 0.693121
    dpo_full_resume_loss: 0.692937
    pt_full_loss: 11.86996
    pt_full_resume_loss: 11.867313
    # test_lora
    sft_lora_loss: 11.944797
    sft_lora_resume_loss: 11.946123
    dpo_lora_loss: 0.693144
    dpo_lora_resume_loss: 0.693138
    pt_lora_loss: 11.975819
    pt_lora_resume_loss: 11.97421
    #test_tp_pp
    sft_full_tp_pp_loss: 11.956945
    sft_full_tp_pp_resume_loss: 11.956932
    dpo_full_tp_pp_loss: 0.693137
    dpo_full_tp_pp_resume_loss: 0.693116
    pt_full_tp_pp_loss: 11.980651
    pt_full_tp_pp_resume_loss: 11.98307
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 11.956937
    sft_lora_tp_pp_resume_loss: 11.956906
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 11.980649
    pt_lora_tp_pp_resume_loss: 11.983072
    #test_fc
    sft_full_function_call_loss: 11.955276
    sft_full_function_call_resume_loss: 11.950663
qwen3_next: 
  repo_id: "PaddleFormers/tiny-random-qwen3next"
  cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 11.944817
    sft_full_resume_loss: 11.946183
    dpo_full_loss: 0.693121
    dpo_full_resume_loss: 0.693068
    pt_full_loss: 11.975817
    pt_full_resume_loss: 11.974206
    # test_lora
    sft_lora_loss: 11.944797
    sft_lora_resume_loss: 11.946123
    dpo_lora_loss: 0.693144
    dpo_lora_resume_loss: 0.693138
    pt_lora_loss: 11.975819
    pt_lora_resume_loss: 11.97421
    #test_tp_pp
    sft_full_tp_pp_loss: 11.956945
    sft_full_tp_pp_resume_loss: 11.956932
    dpo_full_tp_pp_loss: 0.693137
    dpo_full_tp_pp_resume_loss: 0.693116
    pt_full_tp_pp_loss: 11.980651
    pt_full_tp_pp_resume_loss: 11.98307
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 11.956937
    sft_lora_tp_pp_resume_loss: 11.956906
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 11.980649
    pt_lora_tp_pp_resume_loss: 11.983072
    #test_fc
    sft_full_function_call_loss: 11.955276
    sft_full_function_call_resume_loss: 11.950663
phi3:
  repo_id: "PaddleFormers/tiny-random-phi4-bf16"
  cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 11.520309
    sft_full_resume_loss: 11.520774
    dpo_full_loss: 0.693121
    dpo_full_resume_loss: 0.693068
    pt_full_loss: 11.975817
    pt_full_resume_loss: 11.974206
    # test_lora
    sft_lora_loss: 11.944797
    sft_lora_resume_loss: 11.946123
    dpo_lora_loss: 0.693144
    dpo_lora_resume_loss: 0.693138
    pt_lora_loss: 11.975819
    pt_lora_resume_loss: 11.97421
    #test_tp_pp
    sft_full_tp_pp_loss: 11.956945
    sft_full_tp_pp_resume_loss: 11.956932
    dpo_full_tp_pp_loss: 0.693137
    dpo_full_tp_pp_resume_loss: 0.693116
    pt_full_tp_pp_loss: 11.980651
    pt_full_tp_pp_resume_loss: 11.98307
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 11.956937
    sft_lora_tp_pp_resume_loss: 11.956906
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 11.980649
    pt_lora_tp_pp_resume_loss: 11.983072
    #test_fc
    sft_full_function_call_loss: 11.955276
    sft_full_function_call_resume_loss: 11.950663
gemma3_text:
  repo_id: "PaddleFormers/tiny-random-gemma3"
  cli_args: 
    # fuse_attention_qkv: true
    # fuse_attention_ffn: true
    save_checkpoint_format: flex_checkpoint
    load_checkpoint_format: flex_checkpoint
  base_loss: 
    # test_full 
    sft_full_loss: 11.520309
    sft_full_resume_loss: 11.520774
    dpo_full_loss: 0.693121
    dpo_full_resume_loss: 0.693068
    pt_full_loss: 11.975817
    pt_full_resume_loss: 11.974206
    # test_lora
    sft_lora_loss: 11.944797
    sft_lora_resume_loss: 11.946123
    dpo_lora_loss: 0.693144
    dpo_lora_resume_loss: 0.693138
    pt_lora_loss: 11.975819
    pt_lora_resume_loss: 11.97421
    #test_tp_pp
    sft_full_tp_pp_loss: 11.956945
    sft_full_tp_pp_resume_loss: 11.956932
    dpo_full_tp_pp_loss: 0.693137
    dpo_full_tp_pp_resume_loss: 0.693116
    pt_full_tp_pp_loss: 11.980651
    pt_full_tp_pp_resume_loss: 11.98307
    #test_lora_tp_pp
    sft_lora_tp_pp_loss: 11.956937
    sft_lora_tp_pp_resume_loss: 11.956906
    dpo_lora_tp_pp_loss: 11.944916
    dpo_lora_tp_pp_resume_loss: 11.946712
    pt_lora_tp_pp_loss: 11.980649
    pt_lora_tp_pp_resume_loss: 11.983072
    #test_fc
    sft_full_function_call_loss: 11.955276
    sft_full_function_call_resume_loss: 11.950663