name: Build PR CI-Docker

on:
  push:
    branches: [paddleformers, build*]
  pull_request:
  schedule:
    - cron: "5 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  work_dir: /workspace/PaddleHub
  PaddleFormers_ROOT: /workspace/PaddleHub
  TASK: PaddleFormers-CI-${{ github.event.pull_request.number }}-build-docker
  BRANCH: ${{ github.event.pull_request.base.ref }}
  CI_name: build-docker
  no_proxy: "localhost,bj.bcebos.com,su.bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

jobs:
  build-ci-docker:
    name: build-ci-docker
    runs-on: [self-hosted, 4gpu]
    steps:
      - name: Download Code
        env:
          work_dir: ${{ github.workspace }}
        run: |
          sudo rm -rf * .[^.]*
          # wget -q --no-proxy  https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddleFormers.tar --no-check-certificate
          # echo "Extracting PaddleFormers.tar.gz"
          # tar xf PaddleFormers.tar && rm -rf PaddleFormers.tar
          source ${{ github.workspace }}/../../../proxy
          git clone --branch=${BRANCH} https://github.com/PaddlePaddle/PaddleHub.git
          cd PaddleHub
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git pull
          git submodule update --init --recursive --force
          git fetch origin pull/${PR_ID}/head
          git checkout -b PR_${PR_ID} FETCH_HEAD
          git remote add upstream https://github.com/PaddlePaddle/PaddleHub.git
          git fetch upstream ${BRANCH}
          git merge ${BRANCH}
          git diff --numstat ${BRANCH} -- |awk '{print $NF}'
          git log --pretty=oneline -10

      - name: Copy Proxy File
        run: |
          cp ${{ github.workspace }}/../../../proxy ./

      - name: Write Dockerfile Inline
        env:
          work_dir: ${{ github.workspace }}/PaddleHub
        run: |
          cat <<EOF > Dockerfile
          FROM iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5
          COPY proxy /tmp/proxy
          RUN bash -c "source /tmp/proxy"  # 或导出变量
          RUN apt-get update && apt-get install -y libsndfile1 --fix-missing
          RUN unset http_proxy && unset https_proxy
          RUN unlink /usr/bin/python3 && ln -sf python3.10 /usr/bin/python3
          RUN python -m pip config --user set global.index http://pip.baidu-int.com/search/
          RUN python -m pip config --user set global.index-url http://pip.baidu-int.com/simple
          RUN python -m pip config --user set global.trusted-host pip.baidu-int.com
          RUN python -m pip install bce-python-sdk==0.8.74
          RUN python -m pip install --no-cache-dir https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuSome-LinuxCentos-Gcc82-Cuda118-Cudnn86-Trt85-Py310-CINN-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
          COPY PaddleHub /tmp/paddlehub
          WORKDIR /tmp/paddlehub
          RUN python -m pip install -r requirements.txt
          RUN python -m pip install -r requirements-dev.txt
          RUN python -m pip install -r tests/requirements.txt
          RUN python setup.py bdist_wheel > /dev/null
          RUN python -m pip install dist/*.whl
          WORKDIR /
          RUN rm -rf /tmp/paddlehub
          CMD ["python3"]
          EOF
      
      - name: Build Docker Image
        run: |
          docker build -t iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-latest .

      - name: Test CI Image
        run: |
          docker run --rm paddleformers-ci:latest /bin/bash -c "
            python -c \"from paddleformers import __version__; print('paddleformers version:', __version__)\"
            python -c \"import paddleformers; print('paddleformers commit:', paddleformers.version.commit)\"
            python -c \"import paddle; print('paddle'); print(paddle.__version__); print(paddle.version.show())\"
            python -m pip list
          "